#!/sh

unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "\uf05d tmux.conf reloaded"

# General settings
set -g prefix C-a

set -g default-terminal "tmux-256color"
set -g allow-passthrough on
set -g display-time 2000
set -g status-interval 5
set -g base-index 1
set -g pane-base-index 1
set -g mouse on
set -g renumber-windows on
set -g set-clipboard on
set -g automatic-rename on
set -g automatic-rename-format "#{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}}"

set-window-option -g mode-keys vi

# Key bindings
unbind '"'
unbind %
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind X kill-window
bind S run-shell "tmux switch-client -t default \\; kill-session -t '#S'"
bind s display-popup -w 60% -h 70% -E "~/bin/tmux-session-picker"

# Plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'wfxr/tmux-fzf-url'

set -g @fzf-url-fzf-options '-w 50% -h 50% --multi -0 --no-preview'

# Theme
set -g status-style "bg=default"
set -g status-position top
set -g status 2
set -g status-format[1] "#[fg=default,dim]#(printf '%%*s' #{window_width} '' | tr ' ' '─')"
set -g status-left-length 100
set -g status-right-length 100
set -g status-left "#[fg=#{?client_prefix,red,magenta},bold] \uf120 #S #[fg=default,dim]\ue621 "
set -g status-right "#[fg=yellow]#{?#{!=:#{pane_title},#{host}},#{pane_title},} \ue621 #[fg=orange]P-#P"
set -g window-status-current-format "#[fg=blue,bold]\uf444 #I-#W#{?window_zoomed_flag, ,}"
set -g window-status-format "#[fg=white]\uf48b #I-#W"
set -g message-style "fg=cyan,bg=default"
set -g message-command-style "fg=yellow,bg=default"
set -g pane-border-style "fg=colour238"
set -g pane-active-border-style "fg=magenta"

run '/opt/homebrew/opt/tpm/share/tpm/tpm'
